### ISSUE TITLE
リスト詳細ページの実装

### ISSUE THREAD

**Issue by kage622328** [kage622328/did_it#66]
## ブランチ名
feature/list_show_page

## 概要
lists/showページの実装

- [x] ルーティング(children/id/list/show)
- [x] controllers/lists_controllerにshowアクションを追記

### view
- [x] task一覧の表示
- [x] task-btn、task-boxの作成
- [x] task.statusによってbtnとboxの出しわけ
- [x] task全て完了時に"コインを獲得するボタンが表示される"

### task statusの変更機能実装
- [x] ルーティング(task/status_change)を設定
- [x] tasks_controllerにstatus_changeアクションを追加
- [x] 作成後はlists/showページに遷移

確認ポイント

補足
